openapi: 3.0.0
info:
  description: "API for exercises library"
  version: "1.0.0"
  title: "Exercises Library"
  license:
    name: "MIT"
    url: "https://choosealicense.com/licenses/mit/"

# Pas utile pour l'instant mais c'est mieux pour après
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /auth/login:
    post:
      summary: "Logs user into the system"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        '200':
          description: A JSON containing the JWT Token under the token key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWTToken"
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /auth/register:
    post:
      summary: "Creates a new user into the system"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        '200':
          description: OK
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/create_exercise:
    post:
      summary: "Creates a new exercise into the system"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExerciseForm"
      responses:
        '200':
          description: OK
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/exercises/{id}:
    get:
      summary: "Retrieve this specific exercise data"
      parameters:
        - name: id
          in: path
          description: "The exercise ID"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Exercise data inside a JSON"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchableExerciseModel"
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    put:
      summary: "Update this specific exercise data"
      parameters:
        - name: id
          in: path
          description: "The exercise ID"
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExerciseUpdateForm"
      responses:
        '200':
          description: OK
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/search:
    post:
      summary: "Search exercises that matches criteria"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchCriterias"
            examples:
              searchExample1:
                $ref: "#/components/examples/searchExample1"
              searchExample2:
                $ref: "#/components/examples/searchExample2"            
      responses:
        '200':
          description: "An object that contains the results and additionnal information"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/tags:
    post:
      summary: "Submit a tag proposal"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagProposal"
      responses:
        '200':
          description: OK
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    put:
      summary: "Validate or modify a Tag"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TagFull"
      responses:
        '200':
          description: OK
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/tags_categories:
    get:
      summary: "Retrieve only Tag categories"
      responses:
        '200':
          description: "An array of tag categories"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag_Category"
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
  /api/tags_by_categories:
    get:
      summary: "Retrieve Tag categories with their related tags"
      parameters:
        - in: query
          style: form
          name: settings
          explode: true
          schema:
            allOf:
              - type: object
                properties:
                  onlyValidated:
                    type: boolean
                    description: "If true, only consider validated tags by admins. If false, it takes everything"
                    default: true
                  onlySelected:
                    type: array
                    description: "If not empty, only consider the given tag categories ID(S). If empty, no tag category is ignored"
                    default: []
                    items:
                      type: integer
                      example: 42
                      description: "A Tag Category ID"
      responses:
        '200':
          description: "An array of Tag category with their related tags"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TagCategoryWithTags"
        # Definition of all error statuses
        default:
          description: "Whatever error : 4XX - Client error (Bad Request, Unauthorized, etc.) , 5XX - Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
components:
  schemas:
    JWTToken:
      type: object
      properties:
        token:
          type: string
          description: The JWT Token
      required:
        - token
    ErrorObject:
      type: object
      properties:
        message:
          type: string
          description: The main error message ( for example "Bad Request", "Unauthorized", etc. )
        errors:
          type: array
          items:
            type: object
            description: Explanation about an error
      required:
        - message
        - errors
    Auth:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "jy95@perdu.com"
        password:
          type: string
          format: password
          example: "42"
      required:
        - email
        - password
# Basic model of a Exercise 
    BasicExerciseModel:
      type: object
      properties:
        title:
          type: string
          example: "A Super Exercise"
          description: "The title of this exercise"
        description:
          type: string
          example: "..."
          description: "The preamble of this exercise"
      required:
        - title
        - description
# If already in database, we have other fields (in addition of the basic Model)
    AlreadyPresentExerciseModel:
      allOf:
        - $ref: '#/components/schemas/BasicExerciseModel'
        - type: object
          properties:
            id:
              type: integer
              example: 42
              description: "The Id of this exercise"
            version:
              type: integer
              example: 42
              description: "The version of this exercise (optimistic lock)"
            createdAt:
              type: string
              format: date-time
              example: "2019-10-26 21:46:02.325+02"
              description: "Date of creation of this exercise"
            updatedAt:
              type: string
              format: date-time
              example: "2019-10-26 21:46:02.325+02"
              description: "Date of the latest update of this exercise"
          required:
            - id
            - version
            - createdAt
            - updatedAt
# For search / get context, we have other fields (in addition of the AlreadyPresentExerciseModel )
    SearchableExerciseModel:
      allOf:
        - $ref: "#/components/schemas/AlreadyPresentExerciseModel"
        - type: object
          properties:
            metrics:
              type: object
              properties:
                votes:
                  type: integer
                  example: 42
                  description: "Number of votes for this exercise"
                avg_score:
                  type: number
                  format: double
                  example: 5.0
                  description: "The average score of this exercise"
              required:
                - votes
                - avg_score
            tags:
              type: array
              items:
                $ref: '#/components/schemas/TagWithCategory'
# Each exercise has a least one tag
              minItems: 1
          required:
            - metrics
            - tags
# A Tag Category
    Tag_Category:
      type: object
      properties:
        id:
          type: integer
          example: 42
          description: "The Id of this Tag_Category"
        category:
          type: string
          example: "difficulty"
          description: "The text of this Tag_Category"
      required:
        - id
        - category
# A Tag
    Tag:
      type: object
      properties:
        id:
          type: integer
          example: 42
          description: "The Id of this Tag"
        text:
          type: string
          example: "easy"
          description: "The text of this Tag"
      required:
        - id
        - text
# Tag with Tag category
    TagWithCategory:
      allOf:
        - $ref: "#/components/schemas/Tag"
        - type: object
          properties:
            category:
              type: string
              example: "difficulty"
              description: "The text of the Tag Category linked with this tag"
            category_id:
              type: integer
              example: 42
              description: "The category ID linked with this tag"
          required:
            - category
            - category_id
    TagCategoryWithTags:
      allOf:
        - $ref: "#/components/schemas/Tag_Category"
        - type: object
          properties:
            tags:
              type: array
              description: "An array of related tags to this Tag Category"
              minItems: 1
              items:
                $ref: "#/components/schemas/Tag"
# Tag proposal
    TagProposal:
      type: object
      properties:
        text:
          type: string
          example: "easy"
          description: "The text of this Tag"
        category_id:
          type: integer
          example: 42
          description: "the category id to which this tag is related"
      required:
        - text
        - category_id
# Tag updated / validated
    TagFull:
      allOf:
        - $ref: "#/components/schemas/Tag"
        - type: object
          properties:
            category_id:
              type: integer
              example: 42
              description: "the category id to which it is related"
            isValidated:
              type: boolean
              example: false
              description: "Is this tag validated or not"
            version:
              type: integer
              description: "The version of this exercise (optimistic lock)"
              example: 42 
          required:
            - category_id
            - isValidated
            - version
# When we want to upload a new exercise, we need other fields for that
    ExerciseForm:
      allOf:
        - $ref: "#/components/schemas/BasicExerciseModel"
        - type: object
          properties:
            tags:
              type: array
              items:
                oneOf:
                  - type: integer
                    description: "A Tag ID ( already existent in database )"
                  - $ref: "#/components/schemas/TagProposal"
                    description: "A not-existent Tag we want to add"
              description: "Mixed array that contains existent tag(s) or not"
              minItems: 1 # We must always put at least one tag in the database
          required:
            - tags
# When we want to update a already existent exercise, we also need the version
    ExerciseUpdateForm:
      allOf:
        - $ref: "#/components/schemas/ExerciseForm"
        - type: object
          properties:
            version:
              type: integer
              description: "The version of this exercise (optimistic lock)"
              example: 42
          required:
            - version
# Result after a call to /search
    SearchResult:
      type: object
      properties:
        metadata:
          type: object
          description: "Fields for pagination"
          properties:
            currentPage:
              type: integer
              example: 1
              description: "Current number of page"
              default: 1
            totalItems:
              type: integer
              example: 42
              description: "How much exercises match the given criterias"
            totalPages:
              type: integer
              example: 5
              description: "How much pages of exercises match the given criterias"
            pageSize:
              type: integer
              example: 10
              default: 10
              description: "How many entries of exercises on each page"
        data:
          type: array
          items:
            $ref: "#/components/schemas/SearchableExerciseModel" 
            description: "An array of exercise data"
      required:
        - count
        - rows
# Common criteria ( for pagination )
    CommonCriterias:
      type: object
      properties:
        limit:
          type: integer
          description: "Maximal number of items we want to retrieve"
          example: 42
        offset:
          type: integer
          description: "Number of items we want to skip (useful with limit for pagination)"
          example: 42
# Search criteria
    SearchCriterias:
      type: object
      properties:
        metadata:
          type: object
          description: "Fields for pagination"
          properties:
            page:
              type: integer
              description: "Page number (start at 1)"
              default: 1
              example: 1
            size:
              type: integer
              description: "Number of items by page"
              default: 10
              example: 10
        data:
          type: object
          description: "Search criterias"
          properties:
            title:
              type: string
              description: "Something we want to find inside the title of exercises"
              example: "SINF2MS"
            tags:
              type: array
              items:
                oneOf:
                  - type: integer
                    format: int32
                    example: 1
                  - type: array
                    items:
                      type: integer
                      format: int32
                    minItems: 1 # Not allowing empty array if we use
              description: "Tags search encoded in Conjunctive Normal Form. (for NOT predicat, use a negative integer)"
              example: [-1, [2, 3]]
# 1) Define the security scheme type (HTTP bearer)
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

# 2) Apply the security globally to all operations
#security:
#  - bearerAuth: []         # use the same name as above

  examples:
# Examples for /search
    searchExample1:
      description: "Search the first 10 exercises that have 'Java' in their title and have some specific tags ( 1 AND (2 OR 3 OR 4) )"
      value:
        data:
          title: "Java"
          tags: [1, [2, 3, 4]]
    searchExample2:
      description: "Search the exercises on page 2 that have 'Java' in their title but with specific tags ( (NOT 1) AND (2 OR 3)  )"
      value:
        metadata:
          page: 2
          size: 10
        data:
          title: "Java"
          tags: [-1, [2, 3]]