openapi: 3.0.0
info:
  description: "API for Source Code"
  version: "1.0.0"
  title: "Source Code"
  license:
    name: "GPL-3.0-or-later"
    url: "https://choosealicense.com/licenses/gpl-3.0/"

# Pas utile pour l'instant mais c'est mieux pour après
servers:
  - url: http://localhost:3000
    description: Internal staging server for testing
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

# To fast distinguish what could be done by guest, user and admin
tags:
  - name: guest
    description: "Everything a(n) visitor / not authentified user could do"
  - name: user
    description: "Everything an authentified user could do (more than a guest)"
  - name: admin
    description: "Everything an administrator could do (more than an user)"

paths:
  /auth/login:
    $ref: 'openapi/paths/auth.yaml#/paths/~1auth~1login'
  /auth/register:
    $ref: 'openapi/paths/auth.yaml#/paths/~1auth~1register'
  /auth/me:
    $ref: 'openapi/paths/auth.yaml#/paths/~1auth~1me'
  /auth/update:
    $ref: 'openapi/paths/auth.yaml#/paths/~1auth~1update'
  /api/create_exercise:
    $ref: 'openapi/paths/create_exercise.yaml#/paths/~1api~1create_exercise'
  /api/exercises/{id}:
    $ref: 'openapi/paths/exercise.yaml#/paths/~1api~1exercises~1%7Bid%7D'
  /api/search:
    $ref: 'openapi/paths/search.yaml#/paths/~1api~1search'
  /api/tags:
    $ref: 'openapi/paths/tags.yaml#/paths/~1api~1tags'
  /api/tags_categories:
    $ref: 'openapi/paths/tags_categories.yaml#/paths/~1api~1tags_categories'
  /api/tags_by_categories:
    $ref: 'openapi/paths/tags_by_categories.yaml#/paths/~1api~1tags_by_categories'
  /api/bulk/create_exercises:
    $ref: 'openapi/paths/bulk.yaml#/paths/~1api~1bulk~1create_exercises'
  /api/bulk/create_or_find_tag_categories:
    $ref: 'openapi/paths/bulk.yaml#/paths/~1api~1bulk~1create_or_find_tag_categories'
  /api/bulk/modify_exercises_status:
    $ref: 'openapi/paths/bulk.yaml#/paths/~1api~1bulk~1modify_exercises_status'
  /api/bulk/delete_exercises:
    $ref: 'openapi/paths/bulk.yaml#/paths/~1api~1bulk~1delete_exercises'
  /api/vote_for_exercise:
    $ref: 'openapi/paths/vote_for_exercise.yaml#/paths/~1api~1vote_for_exercise'
  /api/configurations:
    $ref: 'openapi/paths/configurations.yaml#/paths/~1api~1configurations'
  /files/{file}:
    $ref: 'openapi/paths/miscellaneous.yaml#/paths/~1files~1%7Bfile%7D'

components:
  securitySchemes:
    bearerAuth:
      $ref: "openapi/security.yaml#/components/securitySchemes/bearerAuth"